import {Material,Warehouse,Stock,StockMovement} from '../models/Inventory.js';
const tid=r=>r.user?.tenantId;const guard=(r,s)=>{if(!tid(r)){s.status(403).json({success:false,message:'Tenant context required',code:'TENANT_REQUIRED'});return false}return true};const scope=(r,x={})=>({tenantId:tid(r),...x});
export const listMaterials=async(r,s,n)=>{try{if(!guard(r,s))return;s.json({success:true,data:await Material.find(scope(r)).sort({name:1}).lean()})}catch(e){n(e)}};
export const createMaterial=async(r,s,n)=>{try{if(!guard(r,s))return;const b=r.body||{};if(!b.sku||!b.name||!b.unit)return s.status(400).json({success:false,message:'SKU, name and unit are required',code:'INVALID_MATERIAL'});s.status(201).json({success:true,data:await Material.create({...b,tenantId:tid(r)})})}catch(e){n(e)}};
export const listWarehouses=async(r,s,n)=>{try{if(!guard(r,s))return;s.json({success:true,data:await Warehouse.find(scope(r)).populate('projectId','name code').sort({name:1}).lean()})}catch(e){n(e)}};
export const createWarehouse=async(r,s,n)=>{try{if(!guard(r,s))return;const b=r.body||{};if(!b.name||!b.code)return s.status(400).json({success:false,message:'Warehouse name and code are required',code:'INVALID_WAREHOUSE'});s.status(201).json({success:true,data:await Warehouse.create({...b,tenantId:tid(r)})})}catch(e){n(e)}};
export const listStock=async(r,s,n)=>{try{if(!guard(r,s))return;s.json({success:true,data:await Stock.find(scope(r)).populate('materialId','sku name unit minimumStock reorderLevel').populate('warehouseId','name code').lean()})}catch(e){n(e)}};
export const recordMovement=async(r,s,n)=>{try{if(!guard(r,s))return;const b=r.body||{},q=Number(b.quantity);if(!b.materialId||!b.warehouseId||!b.type||!Number.isFinite(q)||q<=0)return s.status(400).json({success:false,message:'Material, warehouse, movement type and positive quantity are required',code:'INVALID_MOVEMENT'});const [material,warehouse]=await Promise.all([Material.findOne(scope(r,{_id:b.materialId})),Warehouse.findOne(scope(r,{_id:b.warehouseId}))]);if(!material||!warehouse)return s.status(404).json({success:false,message:'Material or warehouse not found in tenant',code:'INVENTORY_REFERENCE_NOT_FOUND'});if(['TRANSFER_IN','TRANSFER_OUT'].includes(b.type)&&!b.transferWarehouseId)return s.status(400).json({success:false,message:'Transfer warehouse is required for transfers',code:'TRANSFER_WAREHOUSE_REQUIRED'});if(b.transferWarehouseId&&!(await Warehouse.findOne(scope(r,{_id:b.transferWarehouseId}))))return s.status(404).json({success:false,message:'Transfer warehouse not found in tenant',code:'TRANSFER_WAREHOUSE_NOT_FOUND'});const stock=await Stock.findOne(scope(r,{materialId:b.materialId,warehouseId:b.warehouseId}));const current=stock?.quantity||0;if(['ISSUE','TRANSFER_OUT'].includes(b.type)&&current<q)return s.status(409).json({success:false,message:'Insufficient available stock',code:'INSUFFICIENT_STOCK'});const delta=['ISSUE','TRANSFER_OUT'].includes(b.type)?-q:q;const updated=await Stock.findOneAndUpdate(scope(r,{materialId:b.materialId,warehouseId:b.warehouseId}),{$inc:{quantity:delta}},{upsert:true,new:true,setDefaultsOnInsert:true});const movement=await StockMovement.create({...b,quantity:q,performedBy:r.user.id,tenantId:tid(r)});if(b.type==='TRANSFER_OUT'){await Stock.findOneAndUpdate(scope(r,{materialId:b.materialId,warehouseId:b.transferWarehouseId}),{$inc:{quantity:q}},{upsert:true,new:true,setDefaultsOnInsert:true});await StockMovement.create({tenantId:tid(r),materialId:b.materialId,warehouseId:b.transferWarehouseId,projectId:b.projectId,type:'TRANSFER_IN',quantity:q,unitCost:b.unitCost||0,reference:b.reference,reason:b.reason,performedBy:r.user.id,transferWarehouseId:b.warehouseId,date:b.date})}s.status(201).json({success:true,data:{movement,stock:updated}})}catch(e){n(e)}};
export const inventorySummary=async(r,s,n)=>{try{if(!guard(r,s))return;const rows=await Stock.find(scope(r)).populate('materialId','sku name unit minimumStock reorderLevel').populate('warehouseId','name code').lean();const lowStock=rows.filter(x=>x.quantity<=((x.materialId?.reorderLevel??x.materialId?.minimumStock)??0));s.json({success:true,data:{items:rows.length,quantity:rows.reduce((a,x)=>a+x.quantity,0),lowStock:lowStock.length,lowStockItems:lowStock}})}catch(e){n(e)}};
