import {Employee} from '../models/HR.js';import {Payroll,Payslip} from '../models/Payroll.js';
const tenant=req=>req.user?.tenantId;const scoped=(req,extra={})=>({tenantId:tenant(req),...extra});const guard=(req,res)=>{if(!tenant(req)){res.status(403).json({success:false,message:'Tenant context required',code:'TENANT_REQUIRED'});return false}return true};const n=v=>Math.max(0,Number(v)||0);
const calculate=(e,allowances=0,overtimePay=0,deductions=0)=>{const basic=n(e.salary);const gross=basic+n(allowances)+n(overtimePay);const ded=Math.min(gross,n(deductions));return {basicSalary:basic,allowances:n(allowances),overtimePay:n(overtimePay),grossPay:gross,deductions:ded,netPay:gross-ded};};
export const listPayroll=async(req,res,next)=>{try{if(!guard(req,res))return;res.json({success:true,data:await Payroll.find(scoped(req)).sort({periodEnd:-1}).lean()})}catch(e){next(e)}};
export const createPayroll=async(req,res,next)=>{try{if(!guard(req,res))return;const {periodStart,periodEnd,currency='KES',employees=[]}=req.body||{};if(!periodStart||!periodEnd||new Date(periodEnd)<new Date(periodStart))return res.status(400).json({success:false,message:'Valid payroll period is required',code:'INVALID_PAYROLL_PERIOD'});const ids=employees.map(String);const query=scoped(req,ids.length?{_id:{$in:ids}}:{});const staff=await Employee.find(query).lean();const items=staff.map(e=>{const input=employees.find(x=>String(x.employeeId)===String(e._id))||{};return {employeeId:e._id,...calculate(e,input.allowances,input.overtimePay,input.deductions)}});const totals=items.reduce((a,i)=>({gross:a.gross+i.grossPay,deductions:a.deductions+i.deductions,net:a.net+i.netPay}),{gross:0,deductions:0,net:0});const row=await Payroll.create({tenantId:tenant(req),periodStart,periodEnd,currency,items,totals,status:'Pending Approval'});res.status(201).json({success:true,data:row})}catch(e){next(e)}};
export const approvePayroll=async(req,res,next)=>{try{if(!guard(req,res))return;const row=await Payroll.findOneAndUpdate(scoped(req,{_id:req.params.id}),{status:'Approved',approvedBy:req.user.id,approvedAt:new Date()},{new:true});if(!row)return res.status(404).json({success:false,message:'Payroll not found',code:'PAYROLL_NOT_FOUND'});await Payslip.deleteMany(scoped(req,{payrollId:row._id}));if(row.items.length)await Payslip.insertMany(row.items.map(i=>({...i,tenantId:tenant(req),payrollId:row._id,periodStart:row.periodStart,periodEnd:row.periodEnd,currency:row.currency,status:'Generated'})));res.json({success:true,data:row})}catch(e){next(e)}};
export const markPayrollPaid=async(req,res,next)=>{try{if(!guard(req,res))return;const row=await Payroll.findOneAndUpdate(scoped(req,{_id:req.params.id,status:'Approved'}),{status:'Paid',paidAt:new Date()},{new:true});if(!row)return res.status(400).json({success:false,message:'Only approved payroll can be paid',code:'PAYROLL_NOT_APPROVED'});await Payslip.updateMany(scoped(req,{payrollId:row._id}),{$set:{status:'Paid'}});res.json({success:true,data:row})}catch(e){next(e)}};
export const listPayslips=async(req,res,next)=>{try{if(!guard(req,res))return;const filter=scoped(req);if(req.query.employeeId)filter.employeeId=req.query.employeeId;res.json({success:true,data:await Payslip.find(filter).populate('employeeId','firstName lastName employeeNumber').sort({periodEnd:-1}).lean()})}catch(e){next(e)}};
export const payrollSummary=async(req,res,next)=>{try{if(!guard(req,res))return;const rows=await Payroll.find(scoped(req)).lean();const summary=rows.reduce((a,p)=>({gross:a.gross+p.totals.gross,deductions:a.deductions+p.totals.deductions,net:a.net+p.totals.net}),{gross:0,deductions:0,net:0});res.json({success:true,data:{periods:rows.length,...summary}})}catch(e){next(e)}};
