import mongoose from 'mongoose';
const {Schema}=mongoose;
const supplierSchema=new Schema({tenantId:{type:Schema.Types.ObjectId,ref:'Tenant',required:true,index:true},code:{type:String,required:true,trim:true},name:{type:String,required:true,trim:true},email:String,phone:String,address:String,categories:[String],taxNumber:String,status:{type:String,enum:['ACTIVE','SUSPENDED','INACTIVE'],default:'ACTIVE'},performanceScore:{type:Number,min:0,max:100,default:0},notes:String},{timestamps:true});supplierSchema.index({tenantId:1,code:1},{unique:true});
const requestSchema=new Schema({tenantId:{type:Schema.Types.ObjectId,ref:'Tenant',required:true,index:true},requestNumber:{type:String,required:true},projectId:{type:Schema.Types.ObjectId,ref:'ConstructionProject'},requestedBy:{type:Schema.Types.ObjectId,ref:'User',required:true},items:[{materialId:{type:Schema.Types.ObjectId,ref:'Material'},description:{type:String,required:true},quantity:{type:Number,min:0,required:true},unit:String,estimatedUnitCost:{type:Number,min:0,default:0}}],reason:String,status:{type:String,enum:['DRAFT','SUBMITTED','APPROVED','REJECTED','ORDERED','CANCELLED'],default:'DRAFT'},approvedBy:{type:Schema.Types.ObjectId,ref:'User'},approvedAt:Date},{timestamps:true});requestSchema.index({tenantId:1,requestNumber:1},{unique:true});
const quoteSchema=new Schema({tenantId:{type:Schema.Types.ObjectId,ref:'Tenant',required:true,index:true},supplierId:{type:Schema.Types.ObjectId,ref:'Supplier',required:true},requestId:{type:Schema.Types.ObjectId,ref:'PurchaseRequest'},quoteNumber:String,validUntil:Date,items:[{description:String,quantity:{type:Number,min:0},unit:String,unitPrice:{type:Number,min:0}}],tax:Number,discount:Number,total:{type:Number,min:0,default:0},status:{type:String,enum:['RECEIVED','UNDER_REVIEW','SELECTED','REJECTED','EXPIRED'],default:'RECEIVED'}},{timestamps:true});
const poSchema=new Schema({tenantId:{type:Schema.Types.ObjectId,ref:'Tenant',required:true,index:true},poNumber:{type:String,required:true},supplierId:{type:Schema.Types.ObjectId,ref:'Supplier',required:true},projectId:{type:Schema.Types.ObjectId,ref:'ConstructionProject'},requestId:{type:Schema.Types.ObjectId,ref:'PurchaseRequest'},items:[{materialId:{type:Schema.Types.ObjectId,ref:'Material'},description:String,quantity:{type:Number,min:0},unit:String,unitPrice:{type:Number,min:0},receivedQuantity:{type:Number,min:0,default:0}}],subtotal:{type:Number,min:0,default:0},tax:{type:Number,min:0,default:0},total:{type:Number,min:0,default:0},status:{type:String,enum:['DRAFT','PENDING_APPROVAL','APPROVED','ORDERED','PARTIALLY_RECEIVED','RECEIVED','CANCELLED'],default:'DRAFT'},createdBy:{type:Schema.Types.ObjectId,ref:'User'},approvedBy:{type:Schema.Types.ObjectId,ref:'User'},approvedAt:Date},{timestamps:true});poSchema.index({tenantId:1,poNumber:1},{unique:true});
const receiptSchema=new Schema({tenantId:{type:Schema.Types.ObjectId,ref:'Tenant',required:true,index:true},poId:{type:Schema.Types.ObjectId,ref:'PurchaseOrder',required:true},warehouseId:{type:Schema.Types.ObjectId,ref:'Warehouse',required:true},receivedBy:{type:Schema.Types.ObjectId,ref:'User',required:true},items:[{materialId:{type:Schema.Types.ObjectId,ref:'Material'},quantity:{type:Number,min:0,required:true}}],deliveryNote:String,date:{type:Date,default:Date.now},notes:String},{timestamps:true});
const invoiceSchema=new Schema({tenantId:{type:Schema.Types.ObjectId,ref:'Tenant',required:true,index:true},supplierId:{type:Schema.Types.ObjectId,ref:'Supplier',required:true},poId:{type:Schema.Types.ObjectId,ref:'PurchaseOrder'},invoiceNumber:{type:String,required:true},amount:{type:Number,min:0,required:true},tax:{type:Number,min:0,default:0},total:{type:Number,min:0,required:true},dueDate:Date,status:{type:String,enum:['DRAFT','RECEIVED','APPROVED','PARTIALLY_PAID','PAID','OVERDUE','CANCELLED'],default:'RECEIVED'}},{timestamps:true});invoiceSchema.index({tenantId:1,invoiceNumber:1},{unique:true});
export const Supplier=mongoose.models.Supplier||mongoose.model('Supplier',supplierSchema);export const PurchaseRequest=mongoose.models.PurchaseRequest||mongoose.model('PurchaseRequest',requestSchema);export const SupplierQuote=mongoose.models.SupplierQuote||mongoose.model('SupplierQuote',quoteSchema);export const PurchaseOrder=mongoose.models.PurchaseOrder||mongoose.model('PurchaseOrder',poSchema);export const GoodsReceipt=mongoose.models.GoodsReceipt||mongoose.model('GoodsReceipt',receiptSchema);export const SupplierInvoice=mongoose.models.SupplierInvoice||mongoose.model('SupplierInvoice',invoiceSchema);
